#!/usr/bin/expect -f  

set ip [lindex $argv 0 ]
set username [lindex $argv 1 ]
set password [lindex $argv 2 ]

set local_path [lindex $argv 3 ]
set remote_path [lindex $argv 4 ]
set opts [lindex $argv 5 ]

spawn scp ${opts} ${local_path}  ${username}@${ip}:${remote_path} 
expect {
        "*yes/no*" {send "yes\r"; exp_continue}
        "*assword:" {send "$password\r"}
        "*${username}*" {send "\r"}
}

wait

